### ISSUE TITLE
List of Podcasts / Episodes that have issues with Podverse

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse#11]
This could and maybe should be a different Github Issue for each podcast and/or episode, but for now, I'll plan on adding podcasts that have problems with PV here:

"The Invisible Hand: Management, Economics..." - the entire app freezes and will no longer open if you try to subscribe to this podcast

**Comment by kreonjr** [comment]
100% threading issue. There is a problem with the aprsing of the podcast but because the parsing is happening on the main thread, until the parser is done and can report that there was a problem, it blocks the UI

**Comment by kreonjr** [comment]
Does not seem to be a problem any more with the specific Podcast. Leaving issue on in case any other podcasts that create this problem are tested.

**Comment by mitchdowney** [comment]
I'll close this issue. We'll create an issue for each individual podcast as need be.
