### ISSUE TITLE
Completion progress bar for feed parser

### ISSUE THREAD

**Issue by kreonjr** [podverse/podverse#141]
Parsing podcasts and playlists combined as one progress item (1 of 10... etc)

**Comment by mitchdowney** [comment]
I think I could get this done *if* I knew how to solve the issues with dispatch_group and the FeedParser that I'm running into in #150...

**Comment by kreonjr** [comment]
Needs some UI work to be done

**Comment by mitchdowney** [comment]
I think the bugs are fixed with PR #198

**Comment by kreonjr** [comment]
Fixed
