### ISSUE TITLE
CoreData / mutating array crashes

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse#145]

**Comment by mitchdowney** [comment]
@kreonjr hmmm could this be a source of our problem? It appears that the PVDownloader NSURLSession delegate methods are by default put on an NSOperation queue if no delegateQueue is provided.

We can assume the feedParser is running in the background and constantly updating episodes on the FeedParser serial queue. However, when a download is complete, episodes will ALSO be updated within the didFinishDownloadingToURL method, **but on the default NSOperation background queue.**

"By passing nil as the third argument of sessionWithConfiguration:delegate:delegateQueue:, the session creates a serial operation queue for us. This operation queue is used for performing the delegate method calls and completion handler calls."

http://code.tutsplus.com/tutorials/working-with-nsurlsession-part-4--mobile-22545

<img width="1211" alt="screen shot 2016-03-22 at 3 41 04 pm" src="https://cloud.githubusercontent.com/assets/2262919/13967434/17016dbc-f045-11e5-90dc-61b05820b6ca.png">

[Link to code in the coreDataRefactoring branch](https://github.com/podverse/podverse/blob/coreDataRefactoring/podverse/PVDownloader.swift#L37)

**Comment by mitchdowney** [comment]
@kreonjr I tried testing the code in the fork and ran into another crash. Basically I can generate crashes consistently by 1) subscribing to about 10 podcasts, 2) leaving the app and reentering the app, 3) downloading more episodes, and 4) waiting until downloads start to finish.

Waiting until downloads start to finish seems to be key. The crashes most often happen after the did finish downloading part of the PVDownloader.

The FeedParser is setting episode properties on the FeedParserQueue, and the PVDownloader is setting episode properties on an NSOperationQueue...wouldn't that cause a crash? They are both using the same MOC, but changing properties of the same elements from separate threads.

![image](https://cloud.githubusercontent.com/assets/2262919/14020190/16e69d10-f1a4-11e5-9752-e7ba132bcf54.png)

**Comment by kreonjr** [comment]
Gdbyw felicia
