### ISSUE TITLE
Fix refreshControl endRefresh notification on PodcastTableVC and EpisodeTableVC 

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse#150]
I'm not sure how to solve this one...the issue I'm running into is that when I pull down on the refreshControl in the PodcastTableVC, then X number of RSS feeds are parsed on the FeedParser (serial) queue.

I tried dispatch_group but it didn't work for me. I'm not sure how to use the dispatch_group_entry and dispatch_group_leave in the PVFeedParser.

**Comment by kreonjr** [comment]
Fixed
