### ISSUE TITLE
Show a "in progress" indicator when you subscribe to a podcast

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse#162]
If I subscribe to 5 podcasts quickly, but I subscribe to a podcast with a lot of RSS feed data 1st (like Joe Rogan Experience), then I nav to the PodcastTableVC, then the app can take like 20+ seconds before podcasts 2 - 3 - 4 - 5 show up on the PodcastTableVC.

It's easy for the user to think that they the app did not successfully subscribe to podcasts 2 - 3 - 4 - 5 because of this delay. We should provide some kind of indicator to the user that subscriptions are underway...

Something to think about, we may want to further improve this by when subscribing initially just parse the podcast information and NOT it's episode information, then reload the PodcastTableVC. This way we could parse all the podcast info of each quickly, see the Podcasts have been added to the PodcastTableVC, then after that finish parsing the episode information and make it accessible in the UI.

**Comment by mitchdowney** [comment]
This is a nice-to-have but not necessary.

**Comment by mitchdowney** [comment]
This is included in PR #198

**Comment by kreonjr** [comment]
Fixed
