### ISSUE TITLE
PodcastTableVC hangs while podcasts are being subscribed to

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse#163]
It seems like the Main Thread is getting overloaded. If I subscribe to 5 podcasts (including a big RSS feed like Joe Rogan Experience) then go to PodcastTableVC, scrolling goes very slowly.

Also, if I subscribe to 10 podcasts then restart the app, the PodcastTableVC scrolls very slowly.

**Comment by kreonjr** [comment]
This should be fixed with the new imaging code

**Comment by mitchdowney** [comment]
The change in [this commit](https://github.com/podverse/podverse/pull/179/commits/0e0793488de449f755ff44e1652ad2f5cd49964a) seems to have prevented the UI from hanging like 90% of the time. I think this is good enough for now.

**Comment by kreonjr** [comment]
Closing for now. if it becomes an issue again we will create a new issue card to further improve hanging
