### ISSUE TITLE
Downloaded mp3s no longer save

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse#172]
I've run into a strange and serious bug...I am subscribed to 8 podcasts and have a few episodes downloaded in each, but now I cannot download anything successfully. I can press the DL button and watch the DL progress go all the way to Finished, but I can see in XCode that the PVDownloader NSURLSession goes to the didFinishWithError protocol method...and worst of all the error within that protocol method is nil, so I have no idea what is causing this to happen.

**Comment by mitchdowney** [comment]
Ah the didFinishWithError protocol method seems to get called every time right after the kDownloadHasFinished postNotification line:

![image](https://cloud.githubusercontent.com/assets/2262919/15361629/dedea872-1cd7-11e6-9a0c-8f3a987c9fd1.png)

After that line the downloader jumps into didFinishWithError, and the error is "nil". But didFinishDownloading then continues and completes the UILocalNotification code. Very strange...

**Comment by mitchdowney** [comment]
CORRECTION: I CAN successfully download older episodes, but for some reason the most recent episodes cannot be downloaded. It is as if the app worked for downloading the most recent episode the first time I subscribed to a podcast, but then when a new episode appears in its RSS feed a few days later, it will not successfully download that episode.

A good podcast for reproducing this is The Dave Ramsey Show, since he releases new episodes almost every day.

**Comment by mitchdowney** [comment]
@kreonjr the work we did previously on this apparently did not work in my tests. This is pretty much the highest priority issue right now.

**Comment by kreonjr** [comment]
Should be fixed in https://github.com/podverse/podverse/pull/186
