### ISSUE TITLE
Beta Login Screen - Ask for the user's email address when they use the app for the first time

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse#175]
User should have the option to create a Podverse account, or Use without Logging In

We may want to add a Settings tab as well, so that you can change your email address / login / logout etc.

**Comment by mitchdowney** [comment]
Pushed with this PR: "Login screen / Post userEmail to server / Fix RightBarButton"

**Comment by kreonjr** [comment]
Looks good
