### ISSUE TITLE
Starting a new episode or clip does not stop the episode/clip that is currently playing

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse#180]
This one is literally driving me crazy due to multiple podcasts playing at the same time and sleep deprivation. 

With code currently on the branch "loginScreen", if you play an episode, then play another episode, then both episodes will play simultaneously.

**Comment by kreonjr** [comment]
Fixed https://github.com/podverse/podverse/pull/181

**Comment by mitchdowney** [comment]
Thanks :D
