### ISSUE TITLE
Adding Auth0 Lock submodule causes app to fail

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse#206]
Whenever I try to add the [Auth0 Lock submodule](https://github.com/auth0/Lock.iOS-OSX), the app no longer builds, and no descriptive error message is provided. Breakpoints are not triggered by Xcode...

Auth0's docs explain the submodule can be installed with Carthage and CocoaPods, but I see no info on how to install without those tools. Do we need to use one of those for this one module?

@kreonjr is there a Xcode debugging technique I should know about that would give me a more descriptive error message than an immediate build failed?

**Comment by mitchdowney** [comment]
Ahh, I can see more error info now. I'd never clicked the speech bubble button...

![image](https://cloud.githubusercontent.com/assets/2262919/17465762/d783dcae-5cc5-11e6-9474-0e52f7eb6674.png)

**Comment by kreonjr** [comment]
Added as a pod
