### ISSUE TITLE
Feedparser - Get the episode duration

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse#24]
Elements of the UI currently depend on an episode having an episode.duration value. Previously the duration was stored in seconds (so 1:30 timestamp = 90 seconds), then converted out of seconds into a timestamp string as needed. 

The duration of a podcast is available on at least some RSS feeds with the itunes:duration property:

![image](https://cloud.githubusercontent.com/assets/2262919/10597211/ff234d4e-76b1-11e5-9d1c-1d7ee541c203.png)

The feedparser uses seconds rather than timestamps, and I believe that is why I decided to store duration in seconds instead of as a timestamp.

I wanted to extend the CustomFeedParser, but I wasn't sure how to handle the <itunes:duration> attribute using the patterns currently in SwiftFeedParser.

Once we grab the duration from the attribute, we should be able to convert the duration hh:mm:ss string into seconds by using the existing PVUtility.convertHHMMSSStringToNSNumber()

For reference, you can find an <itunes:duration> example in the [Duncan Trussell Family Hour RSS feed](http://lavenderhour.libsyn.com/rss).

**Comment by kreonjr** [comment]
Fixed by adding an extra variable to the feedItem class for duration and updating the path pattern detection in the feedparser subclass
