### ISSUE TITLE
Many podcasts episode feeds do not get parsed by the FeedParser

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse#25]
Most of the NPR podcasts I tried to subscribe to ended up parsing the podcast information, but did not parse the episode information. 

Successfully parsed example
NPR Wait Wait...Don't Tell Me! gets successfully parsed, both podcast info and episodes info.
RSS: http://www.npr.org/rss/podcast.php?id=344098539

Unsuccessfully parsed example
NPR Car Talk does not get successfully parsed, the podcast succeeds but the episodes do not.
RSS: http://www.npr.org/rss/podcast.php?id=510208

**Comment by kreonjr** [comment]
Solved by adding more data to the overridden feedparser subclass method
