### ISSUE TITLE
Some podcasts do not parse duration

### ISSUE THREAD

**Issue by kreonjr** [podverse/podverse#27]
I have looked at the xml data on a web browser for i.e Joe Rogans podcast 
( http://joeroganexp.joerogan.libsynpro.com/irss ) and although each item has an itunes:duration property like all other rss feeds I have seen but for some reason, duration is not read for this podcast by the app.It just decides to skip it. and go from enclosures directly to itunes:explicit.
I wonder if I am looking at a different url than the one the app is actually trying to fetch the xml data from...

**Comment by mitchdowney** [comment]
This should be fixed with the latest commits on the mitch branch.
