### ISSUE TITLE
Ignore articles (the, an, a) from titles when sorting podcasts on the podcast page

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse#29]
I'm not sure what a good way to do this is. We could add a property to the podcast class called "sortableTitle", where we store a modified version of the title with the articles moved to the end of the title, but I'm not sure that smells right...

**Comment by mitchdowney** [comment]
I imagine this should be very easy, but @kreonjr next time we talk I'd like to find out how you'd recommend implementing this.

**Comment by kreonjr** [comment]
@mitchdowney Can you please post an example where this is an issue so that I can test it once I implement the sorting

**Comment by mitchdowney** [comment]
Sure, with these articles ignored when sorting, we should get a list like this:

The Bryan Callen Show
Dan Carlin's Hardcore History
The Duncan Trussell Family Hour
The Joe Rogan Experience
StarTalk Radio
The Tim Ferris Show

**Comment by kreonjr** [comment]
Perfect. Here is the PR https://github.com/podverse/podverse/pull/71

**Comment by kreonjr** [comment]
Merged
