### ISSUE TITLE
Build the PVClipper and MakeClipMenu for handling creating, deleting, and editing clips

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse#37]
This could/should get broken down into sub-issues. @kreonjr started making a new Navigation Controller based UI for the MakeClipMenu, but it looks like we didn't commit that code.

Since it's an essential service I'd like to talk about how to proceed with the PVClipper before beginning.

**Comment by kreonjr** [comment]
Navigation items added for he clipper. Most UI for selecting start end time is added. Logic for time calculations is still needed. Not complete yet but its getting there.

**Comment by kreonjr** [comment]
Creating clips functionality implemented. Discussion on editing and deleting clips still needed

**Comment by mitchdowney** [comment]
@kreonjr maybe we can close this issue after we enable the app to make POST requests to the clip repo API.

**Comment by mitchdowney** [comment]
I'm going to close this issue. We can reopen it when we have more specific tasks to implement related to clip making.
