### ISSUE TITLE
Remove !s (forced unwraps) from the PVDownloader

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse#41]
After the app crashed it apparently failed to completely parse and save episodes. On reboot the PVDownloader attempted to startDownloadingEpisode, but it crashed again because it attempted to unwrap an Optional that was nil.

I am thinking that we should refactor the PVDownloader so that we never force unwrap.

**Comment by mitchdowney** [comment]
@kreonjr 

Do we need to use an if let here? Or does the fact it is in a "try" statement make it ok to use ! to force unwrap?

```
                do {
                    try fileManager.removeItemAtPath(destinationURL!.path!)
                } catch {
                    print(error)
                }
```

**Comment by kreonjr** [comment]
Quick answer is yes you should still unwrap.
```
if let destination = destinationURL, let path = destination.path {
    do {
        try fileManager.removeItemAtPath(path)
    } catch {
        print(error)
    }
}
```
