### ISSUE TITLE
Feedparser Error - crashes if an item/enclosure length is missing

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse#42]
When I tried to subscribe to the podcast Hello Internet, the app crashed at this point:

![image](https://cloud.githubusercontent.com/assets/2262919/10838247/5bc0cb8a-7e91-11e5-96b5-befa24e99547.png)

Hello Internet's RSS feed format looks very unusual. Their enclosures have urls, but they don't have lengths or types. Ideally the Feedparser will not crash if we attempt to parse a podcast that doesn't have an enclosure with the length attribute.

**Comment by kreonjr** [comment]
Fixed with PR: https://github.com/podverse/podverse/pull/70
