### ISSUE TITLE
Add missing constraints to all views 

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse#58]
Fix all these horrible yellow exclamation points:

![image](https://cloud.githubusercontent.com/assets/2262919/11925503/84d07e80-a781-11e5-9b51-8699e80c2723.png)

**Comment by mitchdowney** [comment]
I got rid of 20 warnings:

![image](https://cloud.githubusercontent.com/assets/2262919/11947039/1f841ca2-a827-11e5-9e95-122b62b98f4b.png)

@kreonjr a majority of the warnings left are related to the Make Clip view. I'm not sure how to set the constraints within this fancy container view.

**Comment by kreonjr** [comment]
Fixed in this PR: https://github.com/podverse/podverse/pull/69

**Comment by mitchdowney** [comment]
thanks!
