### ISSUE TITLE
Check for new episodes and download new episodes when the app is closed

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse#62]
This is an essential feature of podcast apps, but I'm not sure how they implement it. I think @kreonjr mentioned they might use some kind of push notification approach?

Currently the app will only check for new episodes and download them when you bring the app to the foreground. It will continue downloading episodes when you move it to the background, but it won't continue checking for new episodes when you move it to the background.

**Comment by kreonjr** [comment]
After some more extensive research, this is not possible unfortunately. Apple only allows very specific tasks to be ran in the background when an app is closed and none of those include custom code. 

That being said, I have come up with a nice idea as to how to kind of implement this method. It will require the user to open the app but it will not be necessary to have him manually check for any new episodes. 

As soon as the app launches, it checks for new episodes and if it does find new episodes, it displays a notification badge on the podcast tab item in the bottom. giving this way the user the message that there are new episodes to download. 1 badge per podcast that has new episodes.

**Comment by mitchdowney** [comment]
Thanks so much for looking into this. 

Hmmm, do you think it could be that my other podcast app is always open in the background, and so it is able to carry out episode downloads when it seems like the app is closed? 

I get a few notifications a day from my other podcast app that says "X new episodes are available" and then a notification shortly afterwards that says "X new episodes downloaded". This exact functionality isn't needed right now, but I am curious how they implement that.

In any case the approach you're describing sounds good.

**Comment by mitchdowney** [comment]
Feeds are currently refreshed and new episodes are downloaded 1) when the app loads and 2) when the app enters the foreground. This should be sufficient.

A user can also pull down to refresh all podcast feeds from the PodcastTableVC.
