### ISSUE TITLE
Save playbackPosition every 30 seconds that the media player has been running

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse#90]
The intention of this feature is to provide an approximate back up for the saved playbackPosition (which is used for continuing an episode from where you left off).

Currently the app only saves playbackPosition when you play/pause or skip forward/backward in a now playing episode.

**Comment by mitchdowney** [comment]
@kreonjr would it be inefficient to create a 30 second repeated timer whenever the media player plays, and each time it starts the playbackPosition time is saved?

**Comment by kreonjr** [comment]
It would be kind of wasteful yes but If there is no other way, I guess we can work with it. But first, what are the cases where we would want to have this position? (excluding crashes obviously)

**Comment by mitchdowney** [comment]
Other than crashes I'm not sure at this point. I haven't experienced the issue in over a week, so I'll leave this in the backlog and make note if it happens again.

**Comment by mitchdowney** [comment]
I'll close this and reopen it if we identify a need for it.
