### ISSUE TITLE
Enable clip playback from ClipsTableViewController

### ISSUE THREAD

**Issue by mitchdowney** [podverse/podverse#96]

**Comment by mitchdowney** [comment]
This is beginning to work with the latest commits to the branch setupClipsTable, but right now I'm stumped on how to remove the endtime observer.

@kreonjr, do you have any ideas how we should go about removing an observer within its own completion block? The following works for ending a clip at the appropriate time, but the endtime observer persists...

```
avPlayer.addBoundaryTimeObserverForTimes([endTimeValue], queue: dispatch_get_main_queue()) { () -> Void in
    self.playOrPause()
    // TODO: how do we remove the observer within its own closure???
}
```

**Comment by kreonjr** [comment]
Does self.avPlayer.removeTimeObserver(self) not work right under the self.playPause() method? I am suggesting only by seeing this. I am not 100% sure what we are trying to accomplish here

**Comment by mitchdowney** [comment]
This is ready for review. It is, however, a beast to review. I added a PVClipStreamer class to separate it from the other files.

I think we can hold off on reviewing this code in depth since clip streaming can be disabled if it's problematic. Making the app secure and enabling the app to make POSTs to the web app would be higher priority right now.
